---
language: node_js
node_js:
  - "4"

addons:
  firefox: latest

sudo: false

branches:
  only:
    - master # otherwise pull requests get built twice

cache:
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=ember-data-2.5.x
  - EMBER_TRY_SCENARIO=ember-data-2.6.x
  - EMBER_TRY_SCENARIO=ember-data-2.7.x
  - EMBER_TRY_SCENARIO=ember-data-2.8.x
  - EMBER_TRY_SCENARIO=ember-data-beta
  - EMBER_TRY_SCENARIO=ember-data-canary
  - EMBER_FASTBOOT=2.8.0
  - EMBER_FASTBOOT=canary

matrix:
  fast_finish: true
  allow_failures:
    - env:
      - EMBER_TRY_SCENARIO=ember-data-canary
      - EMBER_FASTBOOT=canary

before_install:
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # wait for xfvb to start up
  # - ./node_modules/ember-cli/node_modules/testem/testem.js launchers

install:
  - npm install
  - bower install

script:
  - npm run legacy
  - if [ "$EMBER_FASTBOOT" ]; then ember fastboot:test --ember-version $EMBER_FASTBOOT; else ember try:one $EMBER_TRY_SCENARIO --skip-cleanup; fi
